#Inventario de JeanOS Shop
[all:vars]
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

#Nodo master
[k8s_master]
k8s-master01 ansible_host=192.168.41.154

#Nodo worker
[k8s_workers]
k8s-worker01 ansible_host=192.168.41.157
k8s-worker02 ansible_host=192.168.41.158

#Todos los nodos de Kubernetes
[k8s_cluster:children]
k8s_master
k8s_workers
