apiVersion: v1
kind: Service
metadata:
  name: jeanos-frontend-service
  namespace: jeanos-shop
  labels:
    app: jeanos-frontend
spec:
  type: NodePort
  selector:
    app: jeanos-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
